spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

wix:
  germany:
    siteId: ${WIX_GER_SITE_ID}
  canada:
    siteId: ${WIX_CAN_SITE_ID}
  key: ${WIX_API_KEY}

pdf:
  key: ${PDF_KEY}
  secret: ${PDF_SECRET}
  workspace-id: ${PDF_TEMPLATE_ID}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  auth: true
  starttls: mail.smtp.starttls.enable
  confirmation: true
  setFrom: ${MAIL_USERNAME}

sendpulse:
  clientId: ${SEND_PULSE_CLIENT_ID}
  clientSecret: ${SEND_PULSE_CLIENT_SECRET}