### Add new profession
POST localhost:8080/api/profession
Content-Type: application/json

{
  "name": "Инженер"
}


### Update profession
PUT http://localhost:8080/api/profession/1
Content-Type: application/json

{
  "name": "Инженер-конструктор"
}


### Get all profession
GET localhost:8080/api/profession/all


### Get profession
GET localhost:8080/api/profession/1


### Delete profession
DELETE localhost:8080/api/profession/1
