### Add new driverLicence
POST localhost:8080/api/driverlicence
Content-Type: application/json

{
  "name": "C"
}


### Update driverLicence
PUT http://localhost:8080/api/driverlicence/1
Content-Type: application/json

{
  "name": "B"
}


### Get all driverLicence
GET localhost:8080/api/driverlicence/all


### Get driverLicence
GET localhost:8080/api/driverlicence/1


### Delete driverLicence
DELETE localhost:8080/api/driverlicence/1
