### Create ForeignLanguageLevel
POST localhost:8080/api/languageLevel
Content-Type: application/json

{
  "name": "A"
}

###Update ForeignLanguageLevel
PUT localhost:8080/api/languageLevel/1
Content-Type: application/json

{
  "name": "Updated A"
}

###Delete ForeignLanguageLevel
DELETE localhost:8080/api/languageLevel/1