### Get all hard-skills
GET localhost:8080/api/hard-skill


### Get one hard-skill
GET localhost:8080/api/hard-skill/1

### Create hard-skill
POST localhost:8080/api/hard-skill
Content-Type: application/json

{
  "name": "Test hard-skill"
}

### Update hard-skill
PUT http://localhost:8080/api/hard-skill/16
Content-Type: application/json

{
  "name": "Updated hard-skill"
}

### Delete hard-skill
DELETE localhost:8080/api/hard-skill/16


