### Get all soft-skills
GET localhost:8080/api/soft-skill


### Get one soft-skill
GET localhost:8080/api/soft-skill/1

### Create soft-skill
POST localhost:8080/api/soft-skill
Content-Type: application/json

{
  "name": "Test soft-skill"
}

### Update soft-skill
PUT http://localhost:8080/api/soft-skill/16
Content-Type: application/json

{
  "name": "Updated soft-skill"
}

### Delete soft-skill
DELETE localhost:8080/api/soft-skill/16


